auditor:
  config:
    applicationName: "client-example"
    eventSource:
      type: USER
      metadata:
        id: "Junk"
    metadata:
      itemId: ${itemNumber}-AND-MODEL-${model}
      noId: NoFetchingHere!
    filters:
      event:
        enabled: false
        type:
          - UPDATED
      element:
        enabled: true
        types:
          - InclusionFilter
          - ExclusionFilter
        options:
          excludes:
            - description
      logging:
        enabled: true
  producer:
    enabled: true
    bootstrapServers: "localhost:9092"
    topic: testTopic
    configs:
      acks: 0
      batch.size: 1
      buffer.memory: 33554432
      client.id: client-example
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      max.block.ms: 1000
      max.in.flight.requests.per.connection: 1
      retries: 0
      value.serializer: org.apache.kafka.common.serialization.StringSerializer

