auditor:
  config:
    applicationName: "client-example"
    eventSource:
      type: USER
      metadata:
        id: ${rand.id}
    metadata:
      itemIdAnything: ${itemNumber}-AND-MODEL-${model}
      noId: NoFetchingHere!
    filters:
      event:
        enabled: false
        type:
          - UPDATED
      element:
        enabled: false
        types:
          - InclusionFilter
          - ExclusionFilter
        options:
          excludes:
            - description
          includes:
            - model
            - price
      logging:
        enabled: true
  producer:
    enabled: true
    bootstrapServers: "localhost:9092"
    topic: auditTopic
    configs:
      client.id: client-example




